updated cart icons to material-ui icons
legendarykamal/Lets-go-shop pull request #15
Opened 2022-08-19 03:12 UTC by ItzNesbroDev

Updated cart ion icons to material ui icon!

2022-08-19 05:00 UTC, legendarykamal requested changes
Please use 
![image](https://user-images.githubusercontent.com/95926324/185545890-e8605adf-256d-449a-a2d4-f92314d50931.png)
for adding icon and 
![image](https://user-images.githubusercontent.com/95926324/185546064-f521cb3c-0d3d-4483-8728-63c5f41fad51.png)
for decreasing on Cart page

2022-08-19 05:02 UTC, legendarykamal commented
Also @ItzNesbroDev  replace cross icon with this delete , It will look more finer. 

![image](https://user-images.githubusercontent.com/95926324/185546232-9dd230d1-d314-49fc-ac7a-e34efb09f214.png)

2022-08-19 05:03 UTC, legendarykamal requested changes
Try to use red and green colour instead of primary.

2022-08-19 11:16 UTC, ItzNesbroDev commented
Ok

2022-08-19 12:36 UTC, ItzNesbroDev commented
@legendarykamal Updated!

2022-08-19 12:51 UTC, legendarykamal requested changes
Just a little more changes to get things done and merged :)

2022-08-19 12:51 UTC, legendarykamal commented on src/App.css
> +  color: rgb(182, 67, 67);
Implementing a darker red colour would be great like using #e32222 for warning

2022-08-19 12:51 UTC, legendarykamal commented on src/App.css
> +  color: green;
red should be used for decrease #e32222

2022-08-19 12:51 UTC, legendarykamal commented on src/components/Cart.js
> -    const productImages = (product) => {
why are you deleting all this logic and then adding the same below ? probably some eslint change?

2022-08-19 12:54 UTC, ItzNesbroDev commented on src/components/Cart.js
> -    const productImages = (product) => {
it was formatted with prettier when save files

2022-08-19 13:01 UTC, legendarykamal commented on src/components/Cart.js
> -    const productImages = (product) => {
ok I have filled a new issue to solve this , pls complete the rest and we will be good to go .

2022-08-19 13:06 UTC, ItzNesbroDev commented on src/components/Cart.js
> -    const productImages = (product) => {
Done!

2022-08-19 14:24 UTC, legendarykamal approved these changes
NIce work :+1:

2022-08-19 14:24 UTC, legendarykamal commented on src/App.css
> +.container-products .delete {
combine .delete and .decrease as these have same properties, rest all looks good .

2022-08-19 15:48 UTC, ItzNesbroDev commented
All Done!

2022-08-19 15:51 UTC, legendarykamal commented on src/App.css
> +.container-products .delete {
@ItzNesbroDev can you delete package-lock.json as its causing some conflicts ? or maybe try to resolve it .

2022-08-20 11:21 UTC, ItzNesbroDev commented on src/App.css
> +.container-products .delete {
Fixed.

2022-08-21 03:59 UTC, ItzNesbroDev commented
@legendarykamal Bro All Done.

2022-08-21 11:16 UTC, legendarykamal approved these changes
LGTM :medal_sports:

2022-08-21 11:16 UTC, legendarykamal commented on src/components/Cart.js
> +          <Delete
For future ref here the new delete icon has been added.

2022-08-21 11:16 UTC, legendarykamal commented on src/components/Cart.js
> +          <RemoveCircleOutline
dec product - sign

2022-08-21 11:17 UTC, merged

2022-08-22 15:59 UTC, legendarykamal commented
congo @ItzNesbroDev You can find your name in the contributors list on the home page :1st_place_medal: