fix : Changed looks of Cart
legendarykamal/Lets-go-shop pull request #33
Opened 2022-08-27 19:41 UTC by IAmTamal

## Description 🗒

 - I have fixed and worked on #31 , you can check out the demo video !
 - I have updated some versions , else app won't start.
 - Sorry for being late, had some emergency health issues.

## Demo 📹

https://user-images.githubusercontent.com/72851613/187045470-d86bbd01-ff1a-4be6-b56a-a9d402df78a2.mp4

## Important  ⚠

 - Updated to `"react-scripts": "5.0.1",`
 - Installed/Updated Material Icons
 
---

**This PR closes #31**

**Regards,**
**Tamal**

2022-09-03 08:25 UTC, legendarykamal requested changes
An add word with a space and then the cart icon would look better :thinking:

2022-09-03 08:26 UTC, legendarykamal requested changes

2022-09-03 08:26 UTC, legendarykamal commented on src/components/Home.js
> +                <a onClick={() => props.addBasket('go')} className="addToCart cart2" href="#"> <AddShoppingCartIcon className='addToCart_icon' /></a>
<a onClick={() => props.addBasket('go')} className="addToCart cart2" href="#"> Add <AddShoppingCartIcon className='addToCart_icon' /></a>

Like this elsewhere too.

2022-09-03 15:22 UTC, IAmTamal commented
Will be done ✅

2022-09-03 20:38 UTC, legendarykamal commented
Nice

On Sat, Sep 3, 2022, 8:52 PM Tamal Das ***@***.***> wrote:

> Will be done ✅
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/legendarykamal/Lets-go-shop/pull/33#issuecomment-1236142325>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AW33QNGW5F77EWHBSN4N72DV4NUL3ANCNFSM57ZZYFUQ>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2022-09-06 15:17 UTC, legendarykamal requested changes
I will say it again , no need to add package-lock.json just copy it from the master branch and replace , inorder words revert those changes they always cause merge conflicts which make it tough to merge your changes as you can see :eye:

2022-09-17 13:56 UTC, closed without merging