Issue#28 solution
legendarykamal/Lets-go-shop pull request #40
Opened 2022-09-10 10:04 UTC by CalebCyrill

**Description**

This PR fixes #28 

**Notes for Reviewers**
Basically removed the padding

2022-09-12 16:28 UTC, legendarykamal requested changes

2022-09-12 16:28 UTC, legendarykamal commented on src/App.css
> -  padding: 50px 60px 0 60px;
what was the reason for removing the left and right padding?

2022-09-12 16:52 UTC, CalebCyrill commented on src/App.css
> -  padding: 50px 60px 0 60px;
the left and right padding was what was causing the buttons to not be uniform until the 300px that was requested. I believe that removing the padding and centering buttons does the same thing that you are wanting without have to worry about the display size.

2022-09-17 13:53 UTC, legendarykamal commented on src/App.css
> -  padding: 50px 60px 0 60px;
yes please put it back and adjust the padding :+1:  @CalebCyrill

2022-09-23 02:16 UTC, merged

2022-09-23 02:19 UTC, legendarykamal commented
Good work, here you go @CalebCyrill feel free to contribute to other issues and improve the site. :)