Material ui button added and are align horizontally
legendarykamal/Lets-go-shop pull request #5
Opened 2022-08-17 07:40 UTC by developer-irfan

Hey!
Material ui button added and are align horizontally. i colored these buttons to orange which looks good you can just change the color what you want.
--Output

![a](https://user-images.githubusercontent.com/111001343/185062229-7da64d99-a8ad-4625-959e-126057b58c70.png)

2022-08-17 11:17 UTC, legendarykamal requested changes
good work just some more changes to look into .

2022-08-17 11:17 UTC, legendarykamal commented on src/components/Navbar.js
> +              startIcon={<ShoppingBasketIcon style={{color:"blue"}} />}
This shopping basket icon is not getting rendered right?

2022-08-17 11:17 UTC, legendarykamal commented on package.json
> +    "@mui/styled-engine-sc": "^5.10.1",
is this needed ?

2022-08-17 11:19 UTC, legendarykamal commented
This is the error that it leads to 
![image](https://user-images.githubusercontent.com/95926324/185105825-354a8703-372e-4240-be86-0842cd98d3cd.png)

If you could resolve this it would work :+1:

2022-08-17 12:11 UTC, developer-irfan commented on src/components/Navbar.js
> +              startIcon={<ShoppingBasketIcon style={{color:"blue"}} />}
@legendarykamal its material ui icon and properly render in my system.

2022-08-17 12:15 UTC, developer-irfan commented
> This is the error that it leads to ![image](https://user-images.githubusercontent.com/95926324/185105825-354a8703-372e-4240-be86-0842cd98d3cd.png)
> 
> If you could resolve this it would work 👍

just install the react/jsx-runtime the error will be gone . 
open cmd and type npm install react/jsx-runtime end enter.

2022-08-17 12:16 UTC, developer-irfan commented on package.json
> +    "@mui/styled-engine-sc": "^5.10.1",
yes its material ui libraries. when you want to use material ui components you must install it.

2022-08-17 12:29 UTC, legendarykamal commented
yes I know @developer-irfan but if that would be the case I wont be able to merge your PR  
either fix this or make a fresh PR as there are little changes to be done in a new branch

2022-08-17 12:29 UTC, kamalbuilds commented on src/components/Navbar.js
> +              startIcon={<ShoppingBasketIcon style={{color:"blue"}} />}
in the ss its not visible

2022-08-17 12:29 UTC, legendarykamal commented on package.json
> +    "@mui/styled-engine-sc": "^5.10.1",
:+1:

2022-08-17 13:58 UTC, developer-irfan commented
> yes I know @developer-irfan but if that would be the case I wont be able to merge your PR either fix this or make a fresh PR as there are little changes to be done in a new branch

This issue solved in my machine by just running mentioned command. If you want more changes to be done then share the details of that changes.

2022-08-18 03:23 UTC, legendarykamal commented
ok just open a new PR for the ```new```  branch , I will merge and resolve all the conflicts there .

2022-08-18 10:14 UTC, legendarykamal commented
@developer-irfan any update?

2022-08-18 11:55 UTC, developer-irfan commented
> @developer-irfan any update?

check now i recently update conflict files like navbar or package.lock.json etc

2022-08-18 16:15 UTC, legendarykamal commented
@developer-irfan we still have many conflicts :eye:

2022-08-18 16:17 UTC, legendarykamal commented
I am closing this for now as its not deploying and has many undesirable conflicts, 
If you want you can make some changes by just copy paste and file a new PR :100:

2022-08-18 16:17 UTC, closed without merging

2022-08-19 05:53 UTC, legendarykamal commented
checking by @Irfo12 are you still working on improving this?